# docker-compose.yml
services:
  web:
    container_name: scheduled-tasks-ai-django
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # Development server
    # Switch to Gunicorn in production:
    # command: gunicorn --bind :8000 settings.wsgi:application  
    volumes:
      - .:/app  # Mount code for live reloading
    ports:
      - "8000:8000"  # Map port 8000 to the host
    env_file: 
      - .env  # Load environment variables from .env
    restart: always
    depends_on:
      - redis
    # - db

  redis:
    image: redis:7-alpine  # Using the official Redis image with Alpine for smaller size
    container_name: scheduled-tasks-ai-redis
    ports:
      - "6379:6379"  # Expose Redis port
    volumes:
      - redis_data:/data  # Persist Redis data
    restart: always

  qcluster:
    image: scheduled-tasks-ai-web  # Use the built image for the web service
    container_name: scheduled-tasks-ai-qcluster
    working_dir: /app
    volumes:
      - .:/app
    command: python manage.py qcluster
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      # - db

  # db:
  #   image: postgres:15-alpine  # Using Alpine-based image for smaller size
  #   container_name: scheduled-tasks-ai-postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data  # Persist database data
  #   env_file:
  #     - .env  # Load environment variables from .env
  #   ports:
  #     - "5432:5432"
  #   restart: always

volumes:
  redis_data:  # Define the named volume for Redis persistence
  # postgres_data:  # Define the named volume for PostgreSQL persistence