apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: scheduled-tasks-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: scheduled-tasks-ai-web:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secrets
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        hostPath:
          path: /app  # We'll adjust this in the overlay configs
