apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - django/deployment.yaml
  - django/service.yaml
  - django/configmap.yaml
  - django/secrets.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
  - qcluster/deployment.yaml
